esphome:
  name: $node_name
  includes:
    - custom_components/functions.h
esp32:
  framework:
    type: esp-idf
external_components:
  - source:
      type: local
      path: custom_components

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Warsaw
  - platform: homeassistant
    id: homeassistant_time

logger:
  level: INFO

  # For S3 UART
  baud_rate: 115200

  # For S3 USB
  #hardware_uart: USB_SERIAL_JTAG

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:
  platform: esphome
web_server:
  port: 80

debug:
  update_interval: 5s

switch:
  - platform: restart
    name: "$node_name restart"
  - platform: factory_reset
    name: "$node_name factory reset"

text_sensor:
  - platform: template
    id: node_name_uppercase
    lambda: |-
      auto nodeName = std::string("$node_name");
      std::transform(nodeName.begin(), nodeName.end(), nodeName.begin(),
               [](unsigned char c){ return std::toupper(c); });

      return nodeName;
    update_interval: 3600s
  - platform: debug
    device:
      name: "$node_name Device Info"
      entity_category: diagnostic
    reset_reason:
      name: "$node_name Reset Reason"
      entity_category: diagnostic

globals:
  - id: last_restart_timestamp
    type: time_t
    restore_value: no
    initial_value: '0'
sensor:
  - platform: debug
    free:
      name: "$node_name Heap Free"
    block:
      name: "$node_name Heap Max Block"
    loop_time:
      name: "$node_name Loop Time"
  - platform: template
    id: last_restart_timestamp_sensor
    name: "$node_name Last Restart Timestamp"
    update_interval: never
    device_class: timestamp

